[package]
name = "pgtest-wire"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "pgtest_pg_wire"

[lints]
workspace = true

[dependencies]
pgtest-utils = { version = "=0.2.0", path = "../pgtest-utils" }
derive_more = { workspace = true, features = ["full"] }
pest = "2.9.1"
pest_derive = "2.9.1"
async-trait = "0.1.92"
bytes = "1.12.1"
pgwire = "0.41.0"
futures = "0.3.34"
tokio-util = { version = "0.7.19", features = ["codec", "rt"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
hotpath = { workspace = true }
pgtest-core = { version = "=0.2.0", path = "../pgtest-core"}
pgtest-engine-backend = { version = "=0.2.0", path = "../pgtest-engine-backend" }

[dev-dependencies]
pgtest-core = { version = "=0.2.0", path = "../pgtest-core", features = ["test-support"] }
tokio-postgres = "0.7.18"
tracing-test = { version = "0.2.6", features = ["no-env-filter"] }
tokio = { workspace = true, features = ["test-util"] }
testcontainers = { workspace = true }
pgtest-database-operations = { version = "=0.2.0", path = "../pgtest-database-operations", features = ["test-support"]}

[features]
default = []
hotpath = ["hotpath/hotpath", "pgtest-core/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc", "pgtest-core/hotpath-alloc"]
hotpath-prometheus = ["hotpath/hotpath-prometheus", "pgtest-core/hotpath-prometheus"]
