[package]
name = "server"
version = "0.2.0"
edition = "2024"
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true


[dependencies]
mimalloc = "0.1.52"
hotpath = { workspace = true }
anyhow = { workspace = true }
envconfig = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
pgtest-core = { version = "=0.2.0", path = "../../crates/pgtest-core" }
pgtest-wire = { version = "=0.2.0", path = "../../crates/pgtest-wire" }
pgtest-database-operations = { version = "=0.2.0", path = "../../crates/pgtest-database-operations" }

[features]
default = []
hotpath = ["pgtest-database-operations/hotpath", "hotpath/hotpath", "pgtest-core/hotpath", "pgtest-wire/hotpath"]
hotpath-alloc = ["pgtest-database-operations/hotpath-alloc", "hotpath", "hotpath/hotpath-alloc", "pgtest-core/hotpath-alloc", "pgtest-wire/hotpath-alloc"]
hotpath-prometheus = ["pgtest-database-operations/hotpath-prometheus", "hotpath", "hotpath/hotpath-prometheus", "pgtest-core/hotpath-prometheus", "pgtest-wire/hotpath-prometheus"]
