[package]
name = "pgtest-core"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "pgtest"


[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["full"] }
envconfig = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rustc-hash = "2.1.3"
pgtest-utils = { path = "../pgtest-utils" }
pgtest-engine-backend = { path = "../pgtest-engine-backend" }
hotpath = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tokio-util = { version = "0.7.19", features = ["rt"], optional = true }
futures-util = { version = "0.3.34", optional = true }

[features]
default = ["tokio-runtime"]
tokio-runtime = ["dep:tokio", "dep:tokio-util", "dep:futures-util", "dep:hotpath"]
test-support = []
runtime-tests = ["tokio-runtime", "test-support", "tokio/test-util"]
hotpath = ["tokio-runtime", "hotpath/hotpath"]
hotpath-alloc = ["hotpath", "hotpath/hotpath-alloc"]
hotpath-prometheus = ["hotpath", "hotpath/hotpath-prometheus"]
